import Navbar from '@/components/Navbar/navbar';
import './navStyle.css';
import './globals.css';
import { Providers } from './providers';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
let navbarLinks = [
  {
    url: '/',
    title: 'Home',
    icon: 'Home',
  },
  {
    url: '/admin/usersscreen',
    title: 'Users Screen',
    icon: 'Users',
  },
  {
    url: '/signin',
    title: 'Register',
    icon: 'Register'
  },

];
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`min-h-screen  light antialiased ${inter.className}`}
    >
      <body suppressHydrationWarning={true}>
        <Providers>
          <main id="mainPage" className="w-screen h-screen p-0 m-0 items-center justify-center overflow-scroll text-lightMainColor bg-lightMainBG dark:text-darkMainColor dark:bg-darkMainBG">
            <Navbar navbarLinks={navbarLinks} path={''} locale={'EN'} />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
